### ISSUE TITLE
Apple Predictive Code Completion Model together with Copilot

### ISSUE THREAD

**Issue by salvatoreboemia** [github/CopilotForXcode#23]
Hello

is it possible to use the Predictive Code Completion Model and Copilot in a coexisting mood? Is it possible to choose whether to see the suggestion of one or the other?

<img width="496" alt="frrwfer" src="https://github.com/user-attachments/assets/ef7843c8-7f58-4b48-999e-67bc44c4f322">

<img width="761" alt="Screenshot 2024-11-05 at 15 04 18" src="https://github.com/user-attachments/assets/aac4fcce-db40-4878-925b-8c4a927c3ef3">

Thanks

**Comment by devm33** [comment]
Hi @salvatoreboemia, thanks for trying out Copilot for Xcode!

It's possible to use both at the same time, though I wouldn't necessarily recommend it since they will often overlap each other.

You could use one or both in an on-demand approach, so instead of showing completions while typing it only shows when requested.

In Xcode, this is controlled by `Settings` > `Text Editing` > `Editing` > `Suggest completions while typing`:

![Image](https://github.com/user-attachments/assets/1a9b6333-d9cc-49df-857a-26dcfe3220c4)

Then Xcode predictive completions can be requested manually in Xcode via Editor > Show Completions (keybindings `control`+`space` by default)

In Copilot for Xcode, this is controlled by `Settings` > `Advanced` > `Request suggestions while typing`:

![Image](https://github.com/user-attachments/assets/2e06e6b6-6205-402b-8309-fc85e2529dad)

Then Copilot completions can be requested manually in Xcode via Editor > GitHub Copilot > Get Suggestions (or by setting a key binding in Xcode, there are no key bindings set for extensions by default)
