### ISSUE TITLE
Login trouble

### ISSUE THREAD

**Issue by UNONONAN** [github/CopilotForXcode#39]
**Describe the bug**

copilot extension will not sign in to GitHub Co-pilot. I have given all necessary permissions and can see the menu in the editor but when I try to sign in through the extension, the process hangs. 
[log.txt](https://github.com/user-attachments/files/17962654/log.txt)

**Versions**
- Copilot for Xcode: 0.29
- Xcode: 16.1
- macOS: 15.1.1

**Steps to reproduce**
1. Launch the extension
2. Attempt login from extension screen.

**Screenshots**

<img width="1529" alt="image" src="https://github.com/user-attachments/assets/6225b18a-8e6a-4fec-9b6d-9fab569f40ee">
<img width="1529" alt="image" src="https://github.com/user-attachments/assets/ac4a4165-2bc7-4f9f-985a-801121c0fda3">

**Logs**

**Additional context**

I have been able to auth from my account on another machine.

**Comment by manoloacademia** [comment]
same!

**Comment by devm33** [comment]
@UNONONAN Hi, the issue is that it can't read your `~/.config` directory:

`Error: EACCES: permission denied, open '\/Users\/aaronlikens\/.config\/github-copilot\/versions.json'] {\n  errno: -13,\n  code: 'EACCES',\n  syscall: 'open',\n  path: '\/Users\/aaronlikens\/.config\/github-copilot\/versions.json'`

Could you try removing the `~/.config` directory (⚠ assuming there's nothing besides `github-copilot` in it!) or try fixing the permissions to it.

**Comment by UNONONAN** [comment]
Yes - thanks for the reply! Just a quick chown solved it. I had a couple of other things in there so deleting was not an option. In case anyone else is following, I did the following in terminal:
`sudo chown -R <username> .config`

**Comment by devm33** [comment]
Thanks for confirming @UNONONAN glad it was a simple fix 🎉

**Comment by manoloacademia** [comment]
thank you guys! It was solved 👯
